"""
File: seisplot.py
Author: Uno Vaaland
Description: A program for plotting seismograms generated by SPECFEM3D_GLOBE.
             Handles SAC and ASDF formats.
"""


import sys
import obspy as op


def ReadSeismograms(stations):

    nstations = len(stations)
    st = op.Stream()
    for i, station in enumerate(stations):
        try:
            st += op.read(station)
            st[i].stats.calib = 1.0
            print("[{}/{}] Succesfully read file: {}".format(i+1, nstations, station))
        except IOError:
            print("[{}/{}] Could not read file:   {}".format(i+1, nstations, station))
    return st


if __name__ == '__main__':

    if len(sys.argv) < 2:
        print("usage: python seisplot.py [station_file_names]")
        sys.exit()

    stations = sys.argv[1:]
    st = ReadSeismograms(stations)
    st.plot(color='red')
