#!/bin/bash

#SBATCH -N 1
#SBATCH --ntasks-per-node=36
#SBATCH -t 00:30:00

# load appropriate compilers/libraries
module load intel/16.0.4

# change directory to build (e.g. /p/lscratchh/vaaland1/specfem3d_globe/)
cd "path/to/specfem3d_glob/"

srun -n 144 ./bin/xmeshfem3D
